In [57]:
import numpy as np
import pandas as pd

In [58]:
psd=pd.read_csv('/content/drive/MyDrive/kaggle Files/dataset.csv',na_values={'age':[" ","n.a"],'bmi':[" ","n.a"],
                                                                             'elective_surgery':[" ","n.a"],'ethnicity':[" ","n.a"],
                                                                             'gender':[" ","n.a"],'height':[" ","n.a"],
                                                                             'icu_admit_source':[" ","n.a"],'weight':[" ","n.a"],
                                                                             'apache_2_diagnosis':[" ","n.a"],'apache_3j_diagnosis':[" ","n.a"],
                                                                             'arf_apache':[" ","n.a"],'gcs_eyes_apache':[" ","n.a"],
                                                                             'gcs_motor_apache':[" ","n.a"],'gcs_unable_apache':[" ","n.a"],
                                                                             'gcs_verbal_apache':[" ","n.a"],'heart_rate_apache':[" ","n.a"],
                                                                             'intubated_apache':[" ","n.a"],'map_apache':[" ","n.a"],
                                                                             'resprate_apache':[" ","n.a"],'temp_apache':[" ","n.a"],
                                                                             'ventilated_apache':[" ","n.a"],'d1_diasbp_max':[" ","n.a"],
                                                                             'd1_diasbp_min':[" ","n.a"],'d1_diasbp_noninvasive_max':[" ","n.a"],
                                                                             'd1_diasbp_noninvasive_min':[" ","n.a"],'d1_heartrate_max':[" ","n.a"],
                                                                             'd1_heartrate_min':[" ","n.a"],'d1_mbp_max':[" ","n.a"],
                                                                             'd1_mbp_min':[" ","n.a"],'d1_mbp_noninvasive_max':[" ","n.a"],
                                                                             'd1_mbp_noninvasive_min':[" ","n.a"],'d1_resprate_max':[" ","n.a"],
                                                                             'd1_resprate_min':[" ","n.a"],'d1_spo2_max':[" ","n.a"],
                                                                             'd1_spo2_min':[" ","n.a"],'d1_sysbp_max':[" ","n.a"],
                                                                             'd1_sysbp_min':[" ","n.a"],'d1_sysbp_noninvasive_max':[" ","n.a"],
                                                                             'd1_sysbp_noninvasive_min':[" ","n.a"],'d1_temp_max':[" ","n.a"],
                                                                             'd1_temp_min':[" ","n.a"],'h1_diasbp_max':[" ","n.a"],
                                                                             'h1_diasbp_min':[" ","n.a"],'h1_diasbp_noninvasive_max':[" ","n.a"],
                                                                             'h1_diasbp_noninvasive_min':[" ","n.a"],'h1_heartrate_max':[" ","n.a"],
                                                                             'h1_heartrate_min':[" ","n.a"],'h1_mbp_max':[" ","n.a"],
                                                                             'h1_mbp_min':[" ","n.a"],'h1_mbp_noninvasive_max':[" ","n.a"],
                                                                             'h1_mbp_noninvasive_min':[" ","n.a"],'h1_resprate_max':[" ","n.a"],
                                                                             'h1_resprate_min':[" ","n.a"],'h1_spo2_max':[" ","n.a"],
                                                                             'h1_spo2_min':[" ","n.a"],'h1_sysbp_max':[" ","n.a"],
                                                                             'h1_sysbp_min':[" ","n.a"],'h1_sysbp_noninvasive_max':[" ","n.a"],
                                                                             'h1_sysbp_noninvasive_min':[" ","n.a"],'d1_glucose_max':[" ","n.a"],
                                                                             'd1_glucose_min':[" ","n.a"],'d1_potassium_max':[" ","n.a"],
                                                                             'd1_potassium_min':[" ","n.a"],'apache_4a_hospital_death_prob':[" ","n.a"],
                                                                             'apache_4a_icu_death_prob':[" ","n.a"],'aids':[" ","n.a"],
                                                                             'cirrhosis':[" ","n.a"],'diabetes_mellitus':[" ","n.a"],
                                                                             'hepatic_failure':[" ","n.a"],'immunosuppression':[" ","n.a"],
                                                                             'leukemia':[" ","n.a"],'lymphoma':[" ","n.a"],
                                                                             'solid_tumor_with_metastasis':[" ","n.a"],'apache_3j_bodysystem':[" ","n.a"],
                                                                             'apache_2_bodysystem':[" ","n.a"]})

In [59]:
psd.head(3)  

encounter_id  patient_id  hospital_id   age    bmi  elective_surgery  \
0         66154       25312          118  68.0  22.73                 0   
1        114252       59342           81  77.0  27.42                 0   
2        119783       50777          118  25.0  31.95                 0   

   ethnicity gender  height      icu_admit_source  ...  diabetes_mellitus  \
0  Caucasian      M   180.3                 Floor  ...                1.0   
1  Caucasian      F   160.0                 Floor  ...                1.0   
2  Caucasian      F   172.7  Accident & Emergency  ...                0.0   

  hepatic_failure immunosuppression  leukemia  lymphoma  \
0             0.0               0.0       0.0       0.0   
1             0.0               0.0       0.0       0.0   
2             0.0               0.0       0.0       0.0   

   solid_tumor_with_metastasis  apache_3j_bodysystem  apache_2_bodysystem  \
0                          0.0                Sepsis       Cardiovascular   
1                          0.0           Respiratory          Respiratory   
2                          0.0             Metabolic            Metabolic   

   Unnamed: 83  hospital_death  
0          NaN               0  
1          NaN               0  
2          NaN               0  

[3 rows x 85 columns]

In [60]:
psd.iloc[:,-1].value_counts()

0    83798
1     7915
Name: hospital_death, dtype: int64

In [61]:
psd.isnull().sum()

encounter_id                       0
patient_id                         0
hospital_id                        0
age                             4228
bmi                             3429
                               ...  
solid_tumor_with_metastasis      715
apache_3j_bodysystem            1662
apache_2_bodysystem             1662
Unnamed: 83                    91713
hospital_death                     0
Length: 85, dtype: int64

In [62]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [63]:
psd['ethnicity']=le.fit_transform(psd['ethnicity'])
psd['gender']=le.fit_transform(psd['gender'])
psd['icu_admit_source']=le.fit_transform(psd['icu_admit_source'])
psd['icu_stay_type']=le.fit_transform(psd['icu_stay_type'])
psd['icu_type']=le.fit_transform(psd['icu_type'])
psd['apache_3j_bodysystem']=le.fit_transform(psd['apache_3j_bodysystem'])
psd['apache_2_bodysystem']=le.fit_transform(psd['apache_2_bodysystem'])

In [64]:
col_drop=['encounter_id','patient_id','hospital_id','Unnamed: 83']
psd.drop(columns=col_drop,axis=1,inplace=True)

In [65]:
psd['age'].fillna(psd['age'].median(), inplace=True)
psd['bmi'].fillna(psd['bmi'].median(), inplace=True)
psd['elective_surgery'].fillna(psd['elective_surgery'].median(), inplace=True)
psd['ethnicity'].fillna(psd['ethnicity'].median(), inplace=True)
psd['gender'].fillna(psd['gender'].median(), inplace=True)
psd['height'].fillna(psd['height'].median(), inplace=True)
psd['icu_admit_source'].fillna(psd['icu_admit_source'].median(), inplace=True)
psd['weight'].fillna(psd['weight'].median(), inplace=True)
psd['apache_2_diagnosis'].fillna(psd['apache_2_diagnosis'].median(), inplace=True)
psd['apache_3j_diagnosis'].fillna(psd['apache_3j_diagnosis'].median(), inplace=True)
psd['arf_apache'].fillna(psd['arf_apache'].median(), inplace=True)
psd['gcs_eyes_apache'].fillna(psd['gcs_eyes_apache'].median(), inplace=True)
psd['gcs_motor_apache'].fillna(psd['gcs_motor_apache'].median(), inplace=True)
psd['gcs_unable_apache'].fillna(psd['gcs_unable_apache'].median(), inplace=True)
psd['gcs_verbal_apache'].fillna(psd['gcs_verbal_apache'].median(), inplace=True)
psd['heart_rate_apache'].fillna(psd['heart_rate_apache'].median(), inplace=True)
psd['intubated_apache'].fillna(psd['intubated_apache'].median(), inplace=True)
psd['map_apache'].fillna(psd['map_apache'].median(), inplace=True)
psd['resprate_apache'].fillna(psd['resprate_apache'].median(), inplace=True)
psd['temp_apache'].fillna(psd['temp_apache'].median(), inplace=True)
psd['ventilated_apache'].fillna(psd['ventilated_apache'].median(), inplace=True)
psd['d1_diasbp_max'].fillna(psd['d1_diasbp_max'].median(), inplace=True)
psd['d1_diasbp_min'].fillna(psd['d1_diasbp_min'].median(), inplace=True)
psd['d1_diasbp_noninvasive_max'].fillna(psd['d1_diasbp_noninvasive_max'].median(), inplace=True)
psd['d1_diasbp_noninvasive_min'].fillna(psd['d1_diasbp_noninvasive_min'].median(), inplace=True)
psd['d1_heartrate_max'].fillna(psd['d1_heartrate_max'].median(), inplace=True)
psd['d1_heartrate_min'].fillna(psd['d1_heartrate_min'].median(), inplace=True)
psd['d1_mbp_max'].fillna(psd['d1_mbp_max'].median(), inplace=True)
psd['d1_mbp_min'].fillna(psd['d1_mbp_min'].median(), inplace=True)
psd['d1_mbp_noninvasive_max'].fillna(psd['d1_mbp_noninvasive_max'].median(), inplace=True)
psd['d1_mbp_noninvasive_min'].fillna(psd['d1_mbp_noninvasive_min'].median(), inplace=True)
psd['d1_resprate_max'].fillna(psd['d1_resprate_max'].median(), inplace=True)
psd['d1_resprate_min'].fillna(psd['d1_resprate_min'].median(), inplace=True)
psd['d1_spo2_max'].fillna(psd['d1_spo2_max'].median(), inplace=True)
psd['d1_spo2_min'].fillna(psd['d1_spo2_min'].median(), inplace=True)
psd['d1_sysbp_max'].fillna(psd['d1_sysbp_max'].median(), inplace=True)
psd['d1_sysbp_min'].fillna(psd['d1_sysbp_min'].median(), inplace=True)
psd['d1_sysbp_noninvasive_max'].fillna(psd['d1_sysbp_noninvasive_max'].median(), inplace=True)
psd['d1_sysbp_noninvasive_min'].fillna(psd['d1_sysbp_noninvasive_min'].median(), inplace=True)
psd['d1_temp_max'].fillna(psd['d1_temp_max'].median(), inplace=True)
psd['d1_temp_min'].fillna(psd['d1_temp_min'].median(), inplace=True)
psd['h1_diasbp_max'].fillna(psd['h1_diasbp_max'].median(), inplace=True)
psd['h1_diasbp_min'].fillna(psd['h1_diasbp_min'].median(), inplace=True)
psd['h1_diasbp_noninvasive_max'].fillna(psd['h1_diasbp_noninvasive_max'].median(), inplace=True)
psd['h1_diasbp_noninvasive_min'].fillna(psd['h1_diasbp_noninvasive_min'].median(), inplace=True)
psd['h1_heartrate_max'].fillna(psd['h1_heartrate_max'].median(), inplace=True)
psd['h1_heartrate_min'].fillna(psd['h1_heartrate_min'].median(), inplace=True)
psd['h1_mbp_max'].fillna(psd['h1_mbp_max'].median(), inplace=True)
psd['h1_mbp_min'].fillna(psd['h1_mbp_min'].median(), inplace=True)
psd['h1_mbp_noninvasive_max'].fillna(psd['h1_mbp_noninvasive_max'].median(), inplace=True)
psd['h1_mbp_noninvasive_min'].fillna(psd['h1_mbp_noninvasive_min'].median(), inplace=True)
psd['h1_resprate_max'].fillna(psd['h1_resprate_max'].median(), inplace=True)
psd['h1_resprate_min'].fillna(psd['h1_resprate_min'].median(), inplace=True)
psd['h1_spo2_max'].fillna(psd['h1_spo2_max'].median(), inplace=True)
psd['h1_spo2_min'].fillna(psd['h1_spo2_min'].median(), inplace=True)
psd['h1_sysbp_max'].fillna(psd['h1_sysbp_max'].median(), inplace=True)
psd['h1_sysbp_min'].fillna(psd['h1_sysbp_min'].median(), inplace=True)
psd['h1_sysbp_noninvasive_max'].fillna(psd['h1_sysbp_noninvasive_max'].median(), inplace=True)
psd['h1_sysbp_noninvasive_min'].fillna(psd['h1_sysbp_noninvasive_min'].median(), inplace=True)
psd['d1_glucose_max'].fillna(psd['d1_glucose_max'].median(), inplace=True)
psd['d1_glucose_min'].fillna(psd['d1_glucose_min'].median(), inplace=True)
psd['d1_potassium_max'].fillna(psd['d1_potassium_max'].median(), inplace=True)
psd['d1_potassium_min'].fillna(psd['d1_potassium_min'].median(), inplace=True)
psd['apache_4a_hospital_death_prob'].fillna(psd['apache_4a_hospital_death_prob'].median(), inplace=True)
psd['apache_4a_icu_death_prob'].fillna(psd['apache_4a_icu_death_prob'].median(), inplace=True)
psd['aids'].fillna(psd['aids'].median(), inplace=True)
psd['cirrhosis'].fillna(psd['cirrhosis'].median(), inplace=True)
psd['diabetes_mellitus'].fillna(psd['diabetes_mellitus'].median(), inplace=True)
psd['hepatic_failure'].fillna(psd['hepatic_failure'].median(), inplace=True)
psd['immunosuppression'].fillna(psd['immunosuppression'].median(), inplace=True)
psd['leukemia'].fillna(psd['leukemia'].median(), inplace=True)
psd['lymphoma'].fillna(psd['lymphoma'].median(), inplace=True)
psd['solid_tumor_with_metastasis'].fillna(psd['solid_tumor_with_metastasis'].median(), inplace=True)
psd['apache_3j_bodysystem'].fillna(psd['apache_3j_bodysystem'].median(), inplace=True)
psd['apache_2_bodysystem'].fillna(psd['apache_2_bodysystem'].median(), inplace=True)

In [66]:
psd.isnull().sum()

age                            0
bmi                            0
elective_surgery               0
ethnicity                      0
gender                         0
                              ..
lymphoma                       0
solid_tumor_with_metastasis    0
apache_3j_bodysystem           0
apache_2_bodysystem            0
hospital_death                 0
Length: 81, dtype: int64

In [67]:
psd.head()

age        bmi  elective_surgery  ethnicity  gender  height  \
0  68.0  22.730000                 0          2       1   180.3   
1  77.0  27.420000                 0          2       0   160.0   
2  25.0  31.950000                 0          2       0   172.7   
3  81.0  22.640000                 1          2       0   165.1   
4  19.0  27.654655                 0          2       1   188.0   

   icu_admit_source  icu_id  icu_stay_type  icu_type  ...  cirrhosis  \
0                 1      92              0         2  ...        0.0   
1                 1      90              0         5  ...        0.0   
2                 0      93              0         5  ...        0.0   
3                 2      92              0         2  ...        0.0   
4                 0      91              0         5  ...        0.0   

   diabetes_mellitus  hepatic_failure  immunosuppression  leukemia  lymphoma  \
0                1.0              0.0                0.0       0.0       0.0   
1                1.0              0.0                0.0       0.0       0.0   
2                0.0              0.0                0.0       0.0       0.0   
3                0.0              0.0                0.0       0.0       0.0   
4                0.0              0.0                0.0       0.0       0.0   

   solid_tumor_with_metastasis  apache_3j_bodysystem  apache_2_bodysystem  \
0                          0.0                     9                    0   
1                          0.0                     8                    6   
2                          0.0                     5                    3   
3                          0.0                     0                    0   
4                          0.0                    10                    7   

   hospital_death  
0               0  
1               0  
2               0  
3               0  
4               0  

[5 rows x 81 columns]

In [68]:
# psd.to_csv('/content/drive/MyDrive/UCI/psd_nf_data.csv')

In [69]:
x=psd.drop(['hospital_death'],axis=1)
x.head(3)

age    bmi  elective_surgery  ethnicity  gender  height  icu_admit_source  \
0  68.0  22.73                 0          2       1   180.3                 1   
1  77.0  27.42                 0          2       0   160.0                 1   
2  25.0  31.95                 0          2       0   172.7                 0   

   icu_id  icu_stay_type  icu_type  ...  aids  cirrhosis  diabetes_mellitus  \
0      92              0         2  ...   0.0        0.0                1.0   
1      90              0         5  ...   0.0        0.0                1.0   
2      93              0         5  ...   0.0        0.0                0.0   

   hepatic_failure  immunosuppression  leukemia  lymphoma  \
0              0.0                0.0       0.0       0.0   
1              0.0                0.0       0.0       0.0   
2              0.0                0.0       0.0       0.0   

   solid_tumor_with_metastasis  apache_3j_bodysystem  apache_2_bodysystem  
0                          0.0                     9                    0  
1                          0.0                     8                    6  
2                          0.0                     5                    3  

[3 rows x 80 columns]

In [70]:
y=psd.iloc[:,-1].values
y

array([0, 0, 0, ..., 0, 0, 0])

In [71]:
from sklearn.model_selection import train_test_split

In [72]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.4,random_state=10)

In [73]:
# AdaBoostClassifier
from sklearn.ensemble import AdaBoostClassifier
adaboost=AdaBoostClassifier(learning_rate=1)
adaboost.fit(x_train,y_train)

AdaBoostClassifier(learning_rate=1)

In [74]:
y_pred_abc=adaboost.predict(x_test)
y_pred_abc

array([0, 0, 0, ..., 0, 0, 0])

In [75]:
from sklearn import metrics
print(metrics.accuracy_score(y_test,y_pred_abc))

0.9258845336095514


In [76]:
adaboost.score(x_test,y_test)

0.9258845336095514

In [77]:
adaboost.score(x_train,y_train)

0.9263634215930362

In [78]:
from sklearn.metrics import confusion_matrix
cm_abc=confusion_matrix(y_test,y_pred_abc)
cm_abc

array([[33017,   576],
       [ 2143,   950]])

In [79]:
import pickle

In [80]:
filename='/content/drive/MyDrive/kaggle Files/psp_data.sav'
pickle.dump(adaboost,open(filename,'wb'))

In [83]:
adaboost.predict([[68.0,22.73,0,2,1,180.3,1,92,0,2,0.541666667,73.9,113.0,502.01,0,0.0,3.0,6.0,0.0,4.0,118.0,0.0,40.0,36.0,39.3,0.0,68.0,37.0,68.0,37.0,119.0,72.0,89.0,46.0,89.0,46.0,34.0,10.0,100.0,74.0,131.0,73.0,131.0,73.0,39.9,37.2,68.0,63.0,68.0,63.0,119.0,108.0,86.0,85.0,86.0,85.0,26.0,18.0,100.0,74.0,131.0,115.0,131.0,115.0,168.0,109.0,4.0,3.4,0.1,0.05,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,9,0]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([0])

In [84]:
adaboost.predict([[45.0,27.65465458,0,2,1,170.2,3,114,0,0,0.009027778,80.3,116.0,103.01,0,0.0,4.0,6.0,0.0,5.0,82.0,0.0,66.0,14.0,36.9,1.0,65.0,59.0,65.0,59.0,82.0,82.0,93.0,71.0,93.0,71.0,24.0,19.0,97.0,97.0,104.0,98.0,104.0,98.0,36.9,36.9,65.0,59.0,65.0,59.0,82.0,82.0,93.0,71.0,93.0,71.0,24.0,19.0,97.0,97.0,104.0,98.0,104.0,98.0,365.0,288.0,5.2,5.2,0.05,0.02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,0]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([0])

In [85]:
adaboost.predict([[68.0,26.01070291,0,2,0,165.1,1,114,0,0,0.758333333,70.9,113.0,501.06,0,0.0,4.0,6.0,0.0,3.0,136.0,1.0,47.0,42.0,32.1,1.0,48.0,36.0,48.0,36.0,134.0,70.0,78.0,47.0,78.0,47.0,42.0,16.0,100.0,51.0,112.0,74.0,112.0,74.0,39.0,36.2,44.0,36.0,44.0,36.0,100.0,84.0,78.0,47.0,78.0,47.0,29.0,16.0,100.0,78.0,98.0,74.0,98.0,74.0,154.0,63.0,4.0,3.3,0.6,0.51,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9,0]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but AdaBoostClassifier was fitted with feature names
  "X does not have valid feature names, but"


array([1])

In [82]:
# loaded_model=pickle.load(open('/content/drive/MyDrive/kaggle Files/psp_data.sav','rb'))